services:
  scib:
    build: 
      context: scib
    image: bigdatainbiomedicine/sc-scib:1.3
  rpy:
    build: 
      context: rpy
    image: bigdatainbiomedicine/sc-rpy:1.2
  scHPL:
    build: 
      context: scHPL
    image: bigdatainbiomedicine/sc-schpl:1.0
  cellxgene:
    build: 
      context: cellxgene
    image: bigdatainbiomedicine/sc-cellxgene:1.0